import { useState } from "react";
import { fmtValue } from "../format";
import { DEFAULT_MODEL, generateCommentary, loadSavedKey, saveKey } from "../commentary";
import type { Feedback, ModelResponse, Verification } from "../types";

function CommentaryBox({ model }: { model: ModelResponse }) {
  const [key, setKey] = useState(loadSavedKey());
  const [remember, setRemember] = useState(!!loadSavedKey());
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<{ status: string; model?: string; text?: string; error?: string } | null>(null);
  const run = async () => {
    setBusy(true); setResult(null);
    saveKey(key, remember);
    try { setResult(await generateCommentary(model, key.trim())); }
    catch (e: any) { setResult({ status: "error", error: e?.message ?? String(e) }); }
    finally { setBusy(false); }
  };
  return (
    <div className="qual ai">
      <h4>AI analyst commentary</h4>
      {result?.status === "ok" && (<>{result.text?.split(/\n+/).map((p, i) => <p key={i}>{p}</p>)}<p className="muted">Generated by {result.model} from this model's numbers.</p></>)}
      {result?.status === "refused" && <p className="muted">The model declined to comment on this input.</p>}
      {result?.status === "error" && <p className="bad-text">Commentary failed: {result.error}</p>}
      <div className="byok">
        <p className="muted">Generate an analyst-style review of this model with Claude using your own Anthropic API key. The key stays in your browser and is sent only to api.anthropic.com; one review costs a few cents.</p>
        <div className="byok-row">
          <input type="password" placeholder="sk-ant-..." value={key} onChange={(e) => setKey(e.target.value)} autoComplete="off" />
          <label><input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)} /> remember on this device</label>
          <button className="primary" onClick={run} disabled={busy || !key.trim()}>{busy ? "Asking Claude..." : (result ? "Regenerate" : "Generate commentary")}</button>
        </div>
        <p className="muted">Model: {DEFAULT_MODEL}. Repository owners can pre-generate commentary for every company by adding an ANTHROPIC_API_KEY secret to the nightly build.</p>
      </div>
    </div>
  );
}

export function FeedbackPanel({ feedback, verification, llm, model }: { feedback: Feedback; verification: Verification; llm: ModelResponse["llm"]; model: ModelResponse }) {
  return (
    <div className="feedback">
      <div className={`status-banner ${feedback.n_fail > 0 ? "fail" : feedback.n_flag > 0 ? "flag" : "pass"}`}>
        <b>{feedback.status}</b>
        <span>{feedback.n_fail} integrity failure(s), {feedback.n_flag} assumption flag(s)</span>
      </div>
      <div className="verify">
        {verification.status === "verified" && (
          <span className="ok">Formula verification: {verification.cells_checked.toLocaleString()} formula cells recalculated by {verification.engine} match the model engine (max difference {verification.max_abs_diff?.toExponential(1)}).</span>
        )}
        {verification.status === "mismatch" && (
          <span className="bad">Formula verification found {verification.n_mismatches} mismatching cell(s), e.g. {verification.mismatches[0]?.sheet}!{verification.mismatches[0]?.cell}.</span>
        )}
        {verification.status === "skipped" && <span className="warn">Formula verification skipped: {verification.reason}</span>}
      </div>
      <h3>Quantitative checks</h3>
      <table className="checks">
        <thead><tr><th>Check</th><th>Value</th><th>Threshold</th><th>Status</th><th>Why it matters</th></tr></thead>
        <tbody>
          {feedback.quantitative.map((q) => (
            <tr key={q.check} className={q.status.toLowerCase()}>
              <td>{q.check}</td><td className="num">{fmtValue(q.value, q.fmt)}</td><td>{q.threshold}</td>
              <td><span className={`pill ${q.status.toLowerCase()}`}>{q.status}</span></td><td className="why">{q.why}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <h3>Qualitative assessment</h3>
      {feedback.qualitative.map((s) => (
        <div className="qual" key={s.title}>
          <h4>{s.title}</h4>
          <ul>{s.points.map((p, i) => <li key={i}>{p}</li>)}</ul>
        </div>
      ))}
      {llm && llm.status === "ok" ? (
        <div className="qual ai">
          <h4>AI analyst commentary <span className="muted">({llm.model}{(llm as any).generated ? `, ${(llm as any).generated}` : ""})</span></h4>
          {llm.text?.split(/\n+/).map((p, i) => <p key={i}>{p}</p>)}
        </div>
      ) : (
        <CommentaryBox model={model} />
      )}
      {llm && llm.status === "error" && <p className="muted">Pre-generated AI commentary unavailable: {llm.error}</p>}
      <h3>Methodology</h3>
      <ul className="method">{feedback.methodology.map((m, i) => <li key={i}>{m}</li>)}</ul>
    </div>
  );
}
